

### Connecting via SQL


#### Directly

```{r db-connection}
library(RPostgreSQL)

dbcon <- dbConnect(RPostgreSQL::PostgreSQL(),
                dbname = "bety", 
                password = 'bety', 
                host = 'terra-bety.default', 
                user = 'bety', 
                port = 5432)

```

```{sql basic-query, connection = dbcon}
select * from cultivars where name like '%55_(SC56*TX7000%'
```
```{sql basic-query, connection = dbcon}

insert into sites_cultivars (site_id, cultivar_id) values ((select id from sites where sitename = 'MAC Field Scanner Field Plot 35 Season 2'), (select id from cultivars where name = 'RIL_55_(SC56*TX7000)-F10'));
insert into sites_cultivars (site_id, cultivar_id) values ((select id from sites where sitename = 'MAC Field Scanner Field Plot 703 Season 2'), (select id from cultivars where name = 'RIL_55_(SC56*TX7000)-F10'));
```


```{sql basic-query, connection = dbcon}
select variables.name, mean 
  from traits join variables 
  on traits.variable_id = variables.id
  limit 10;

```

```{sql trait-counts, connection = dbcon}
select variables.name, count(*) as n 
  from traits join variables 
  on traits.variable_id = variables.id
  group by variables.name
  order by n desc;

```

### Using the rOpensci "traits" package:


```{r}

library(traits)

options(#betydb_key = readLines('~/.betykey', warn = FALSE),
  betydb_url = "https://betydb.org",
  betydb_api_version = 'beta')

leaf_variables <- betydb_query(table = "variables", limit = 727) %>%
  mutate(variable_id = id) %>%    # We're going to need to be joining based on variable_id later
  select(variable_id, description, name, units) %>%    # Only care about the important stuff
  filter(grepl("leaf",name)) %>%    # Only those variables with "leaf" in the name
  collect()


leaf_traits <- betydb_query(table = "traits", limit = 300) %>%
  inner_join(leaf_variables, by = "variable_id") %>%
  select(name, mean, units, description, date, specie_id, site_id, treatment_id) 

leaf_traits %>%
  transmute(scan_id = paste(specie_id, site_id, treatment_id, date))
```