---
title: "10. Bayesian Analysis"
author: David LeBauer
date: '2017-06-06'
slug: bayesian-analysis
categories: []
tags: [r, statistics]
---


## Bayesian regression


```{r setup, include=FALSE, eval=FALSE}

library(dplyr)
grass_yields <- read.csv('data/grass_yield.csv') %>% 
  filter(genus %in% c("Miscanthus", "Panicum") & age >=3) %>%
  mutate(sqrt_yield = sqrt(yield_annual), 
         genus = as.character(genus), 
         site = as.factor(lat+lon))

```

```{r, eval=FALSE}

library(rstanarm)
options(mc.cores = parallel::detectCores())
glm1 <- stan_glmer(yield_annual ~ fertilizer_n + age + genus:fertilizer_n + genus:age + (1 | site ), #prior = normal(30, 4),
                    
                  data = grass_yields)

glm1
plot(glm1)
plot(glm1, plotfun = 'hist')
pairs(glm1)
posterior_interval(glm1)

summary(glm1)
library(sjPlot)
sjPlot::sjp.lmer(glm1)
```

http://topepo.github.io/caret/train-models-by-tag.html
https://thinkinator.com/2016/01/12/r-users-will-now-inevitably-become-bayesians/

